### ISSUE TITLE
Docs for failure vs error semantics

### ISSUE THREAD

**Issue by jayunit100** [onsi/gomega#135]
I dont think it sais in the gomega docs what an Expect actually does when it evaluates to false.

 (i beleive in all cases it Fails (rather than erroring) a test).  

Should make this explicit.

**Comment by onsi** [comment]
In the Ginkgo context there is no distinction between failing a test and erroring a test.

Would be happy for a PR if you have the time to tweak the language.

**Comment by tony-spataro-rs** [comment]
I was bit by the difference between `Errorf` and `Fatalf` today while using gomega outside of the ginkgo context.

I come from a ginkgo+gomega background, where `Expect` will instantly halt test execution if it fails -- equivalent to `testing.T.Fatalf`.

One of the projects I'm maintaining uses gomega with vanilla `testing` and the developers assumed the failure semantic would be consistent with ginkgo's. As a result, tests fail in mysterious ways (e.g. a HaveLen fails, then we panic because we were relying on HaveLen to guard the next expectation).

It wasn't hard for me to copy/paste gomega's support code into my project and introduce `RegisterFatalTestingT` for my own use; would gomega benefit from something like this? If @onsi thinks it's a decent idea and wants to give me some guidance about the interface he'd like in gomega, I'll be happy to PR a docs change as well as an additional register-er so that people can choose the semantic that's right for them.

**Comment by jim-slattery-rs** [comment]
@tony-spataro-rs I think this discrepancy was fixed in a recent Gomega PR: https://github.com/onsi/gomega/pull/215

Does that address the issue you encountered?

**Comment by tony-spataro-rs** [comment]
Indeed; that does fix my issue. I also expect it would close #195; will comment there.

**Comment by williammartin** [comment]
@jayunit100 @tony-spataro-rs Just doing some housekeeping. Is there anything here that's still an issue for you or can I close this out?

**Comment by xeger** [comment]
Nope #215 was indeed the root cause of this issue.

**Comment by williammartin** [comment]
Alright awesome. I'm going to close this off but feel free to re-open if you have any further questions/comments.

**Comment by jayunit100** [comment]
Thanks !
